// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.jun.chu.java.protobuffer;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  java.util.List<com.jun.chu.java.protobuffer.Person> 
      getPeopleList();
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  com.jun.chu.java.protobuffer.Person getPeople(int index);
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  java.util.List<? extends com.jun.chu.java.protobuffer.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  com.jun.chu.java.protobuffer.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
